import { createMuiTheme } from '@material-ui/core';
import { makeStyles, withStyles } from '@material-ui/core/styles';

export const theme = createMuiTheme({
  typography: {
    fontFamily: '"Helvetica"',
    fontSize: 14,
    h1: {
      // could customize the h1 variant as well
    },
  },
  palette: {
    primary: { main: '#516BF6' },
  },
});

export const useStyles = makeStyles(
  (theme) => ({
    form: {
      '& .MuiTextField-root': {
        margin: theme.spacing(1),
        width: '25ch',
        length: '400ch',
        display: 'flex',
        flexDirection: 'column',
        marginBottom: '30px',
      },
      '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline': {
        borderColor: colors.darkBlue,
      },
      '& .MuiOutlinedInput-input': {
        color: 'black',
      },
      '&:hover .MuiOutlinedInput-input': {
        color: 'black',
      },
      '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-input': {
        color: 'black',
      },
      '& .MuiInputLabel-outlined': {
        color: 'gray',
      },
      '&:hover .MuiInputLabel-outlined': {
        color: 'gray',
      },
      '& .MuiInputLabel-outlined.Mui-focused': {
        color: colors.darkBlue,
      },
    },
    [`form-dropdown`]: {
      minWidth: 120,
      marginRight: 30,
      '& .MuiOutlinedInput-root.Mui .MuiOutlinedInput-notchedOutline': {
        borderColor: 'white',
      },
      '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline': {
        borderColor: 'white',
      },
      '& .MuiOutlinedInput-input': {
        color: 'white',
      },
      '&:hover .MuiOutlinedInput-input': {
        color: 'black',
      },
      '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-input': {
        color: 'white',
      },
      '& .MuiInputLabel-outlined': {
        color: 'white',
      },
      '&:hover .MuiInputLabel-outlined': {
        color: 'white',
      },
      '& .MuiInputLabel-outlined.Mui-focused': {
        color: 'white',
      },
    },
    gridSpacingThree: {
      height: '93vh',
      width: '100%',
      margin: 0,
    },
    signUpForm: {
      marginLeft: '40px',
      display: 'flex',
      width: '30%',
    },
    loginImage: {
      float: 'left',
      paddingRight: '40px',
    },
    loginInSignUpContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: '100%',
    },
    getStarted: {
      color: '#484848',
      marginLeft: '10px',
    },
    loginContainer: {
      width: 'inherit',
      top: '0',
      position: 'fixed',
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: '20px',
    },
    alreadyHaveAccount: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontStyle: 'italic',
    },
    loginSignupWrapperRoot: {
      flexGrow: 1,
      overflow: 'hidden',
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontFamily: 'Roboto',
      color: colors.charcoalGray,
    },
    loginSignupWrapperRoot: {
      overflow: 'hidden',
      height: '100vh',
      width: '100vw',
      position: 'relative',
    },
    formField: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      flexDirection: 'column',
    },
    dashboardContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pastPracticesText: {
      fontSize: '40px',
      color: colors.darkBlue,
    },
    interviewTable: {
      width: 1000,
      margin: 'auto',
      borderWidth: 1,
      borderColor: 'black',
    },
    interviewTableHeader: {
      backgroundColor: colors.darkBlue,
    },
    headerFont: {
      color: 'white',
      fontSize: 15,
      fontWeight: 'bold',
    },
    infoFormDiv: {
      marginBottom: '2px',
      fontWeight: '600',
      //color: `${colors.darkGray}`,
      color: 'rgba(94, 94, 94)',
    },
    infoDropdown: {
      marginRight: '10px',
      marginBottom: '20px',
      paddingLeft: '16px',
      paddingBottom: '8px',
      paddingTop: '8px',
      borderRadius: '5px',
      border: `1px solid ${colors.lightGray}`,
      width: '100%',
      height: '40px',
    },
    starRating: {
      marginTop: '5px',
      marginBottom: '7px',
    },
    interviewLevelDiv: {
      color: `${colors.darkBlue}`,
      fontWeight: 'Bold',
    },
    interviewLevelDesc: {
      color: `${colors.darkGray}`,
      marginBottom: '30px',
    },
    interviewContainer: {
      overflow: 'hidden',
      height: '100%',
      width: '100vw',
      position: 'relative',
    },
    interviewHeader: {
      backgroundColor: colors.darkBlue,
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      height: '10vh',
      alignItems: 'center',
    },
    interviewDetailsContainer: {
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    interviewTextEditor: {
      backgroundColor: 'rgba(30,30,30, 1)',
      height: '100vh',
    },
    interviewOutput: {
      backgroundColor: colors.darkGraySolid,
      bottom: '0',
      position: 'absolute',
      height: '20vh',
      width: '66%',
      marginBottom: '25px',
      borderRadius: '10px',
    },
    interviewOutputHeader: {
      backgroundColor: colors.lightGraySolid,
      width: '100%',
      borderTopLeftRadius: '10px',
      borderTopRightRadius: '10px',
      height: '30%',
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
    },
    textMarginRight: {
      marginRight: '10px',
    },
    interviewWithText: {
      marginLeft: '40px',
      color: 'white',
      fontSize: '30px',
    },
    background: {
      width: '50%',
      height: '80%',
      backgroundColor: `white`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      //justifyContent: "center",
    },
    backgroundHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: 'auto',
      marginBottom: 'auto',
    },
    backgroundForm: {
      width: '50%',
      //height: "30%",
      display: 'flex',
      flexDirection: 'column',
    },
    questionDetailsContainer: {
      marginTop: '30px',
      textAlign: 'left',
      width: '100%',
      height: '72vh',
      overflow: 'scroll',
    },
    questionTopicText: {
      color: colors.darkBlue,
      fontSize: '35px',
      marginBottom: '40px',
      textAlign: 'center',
    },
    funcDescText: {
      fontWeight: 'bold',
      fontSize: '25px',
    },
    questionDescText: {
      color: 'gray',
      fontSize: '18px',
      paddingLeft: '20px',
      paddingRight: '20px',
    },
    questionDescExampleText: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '20px',
      padding: '20px',
    },
    questionDescCodeBlock: {
      padding: '20px',
      color: 'black',
      backgroundColor: colors.lighterGray,
      fontSize: '18px',
      fontFamily:
        'SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace',
      padding: '20px',
      width: '85%',
    },
    answerSolutionContainer: {
      marginTop: '30px',
    },
    questionAnswerButtonHighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.darkBlue,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
      fontWeight: 'bold',
    },
    questionAnswerButtonUnhighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.charcoalGray,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
    },
    questionAnswerButtonContainer: {
      display: 'flex',
      flexDirection: 'row',
      marginTop: '20px',
    },
    runCodeButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 4,
      padding: '2px 20px',
    },
    exitInterviewButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    consoleText: {
      color: 'white',
      marginLeft: '20px',
      fontSize: '25px',
    },
    outputText: {
      color: 'white',
      marginTop: '15px',
      paddingLeft: '20px',
      fontFamily: 'monospace',
      fontSize: '18px',
    },
    languageExitInterviewContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: '20px',
    },
    languageDropdownContainer: {
      marginRight: '25px',
      color: 'white',
    },
    languageDropDown: {
      color: 'white',
    },
    navbarDisplayFlex: {
      display: `flex`,
      justifyContent: `space-around`,
      marginRight: `45px`,
    },
    gridSpacingThree: {
      height: '93vh',
      width: '100%',
      margin: 0,
    },
    signUpForm: {
      marginLeft: '40px',
      display: 'flex',
      width: '30%',
    },
    loginImage: {
      float: 'left',
      paddingRight: '40px',
    },
    loginInSignUpContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: '100%',
    },
    getStarted: {
      color: '#484848',
      marginLeft: '10px',
    },
    loginContainer: {
      width: 'inherit',
      top: '0',
      position: 'fixed',
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: '20px',
    },
    alreadyHaveAccount: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontStyle: 'italic',
    },
    loginSignupWrapperRoot: {
      flexGrow: 1,
      overflow: 'hidden',
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontFamily: 'Roboto',
      color: colors.charcoalGray,
    },
    loginSignupWrapperRoot: {
      overflow: 'hidden',
      height: '100vh',
      width: '100vw',
      position: 'relative',
    },
    gridSpacingThree: {
      height: '93vh',
      width: '100%',
      margin: 0,
    },
    signUpForm: {
      marginLeft: '40px',
      display: 'flex',
      width: '30%',
    },
    loginImage: {
      float: 'left',
      paddingRight: '40px',
    },
    loginInSignUpContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: '100%',
    },
    getStarted: {
      color: '#484848',
      marginLeft: '10px',
    },
    loginContainer: {
      width: 'inherit',
      top: '0',
      position: 'fixed',
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: '20px',
    },
    alreadyHaveAccount: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontStyle: 'italic',
    },
    loginSignupWrapperRoot: {
      flexGrow: 1,
      overflow: 'hidden',
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      fontFamily: 'Roboto',
      color: colors.charcoalGray,
    },
    loginSignupWrapperRoot: {
      overflow: 'hidden',
      height: '100vh',
      width: '100vw',
      position: 'relative',
    },
    formField: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      flexDirection: 'column',
    },
    dashboardContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pastPracticesText: {
      fontSize: '40px',
      color: colors.darkBlue,
    },
    interviewTable: {
      width: 1000,
      margin: 'auto',
      borderWidth: 1,
      borderColor: 'black',
    },
    interviewTableHeader: {
      backgroundColor: colors.darkBlue,
    },
    headerFont: {
      color: 'white',
      fontSize: 15,
      fontWeight: 'bold',
    },
    infoFormDiv: {
      marginBottom: '2px',
      fontWeight: '600',
      //color: `${colors.darkGray}`,
      color: 'rgba(94, 94, 94)',
    },
    infoDropdown: {
      marginRight: '10px',
      marginBottom: '20px',
      paddingLeft: '16px',
      paddingBottom: '8px',
      paddingTop: '8px',
      borderRadius: '5px',
      border: `1px solid ${colors.lightGray}`,
      width: '100%',
      height: '40px',
    },
    starRating: {
      marginTop: '5px',
      marginBottom: '7px',
    },
    interviewLevelDiv: {
      color: `${colors.darkBlue}`,
      fontWeight: 'Bold',
    },
    interviewLevelDesc: {
      color: `${colors.darkGray}`,
      marginBottom: '30px',
    },
    interviewContainer: {
      overflow: 'hidden',
      height: '100%',
      width: '100vw',
      position: 'relative',
    },
    interviewHeader: {
      backgroundColor: colors.darkBlue,
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      height: '10vh',
      alignItems: 'center',
    },
    interviewDetailsContainer: {
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    interviewTextEditor: {
      backgroundColor: 'rgba(30,30,30, 1)',
      height: '100vh',
    },
    interviewOutput: {
      backgroundColor: colors.darkGraySolid,
      bottom: '0',
      position: 'absolute',
      height: '20vh',
      width: '66%',
      marginBottom: '25px',
      borderRadius: '10px',
    },
    interviewOutputHeader: {
      backgroundColor: colors.lightGraySolid,
      width: '100%',
      borderTopLeftRadius: '10px',
      borderTopRightRadius: '10px',
      height: '30%',
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
    },
    textMarginRight: {
      marginRight: '10px',
    },
    interviewWithText: {
      marginLeft: '40px',
      color: 'white',
      fontSize: '30px',
    },
    backgroundContainer: {
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `rgba(67, 67, 125)`,
    },
    background: {
      width: '50%',
      height: '80%',
      backgroundColor: `white`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      //justifyContent: "center",
    },
    backgroundHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: 'auto',
      marginBottom: 'auto',
    },
    backgroundForm: {
      width: '50%',
      //height: "30%",
      display: 'flex',
      flexDirection: 'column',
    },
    questionDetailsContainer: {
      marginTop: '30px',
      textAlign: 'left',
      width: '100%',
      height: '72vh',
      overflow: 'scroll',
    },
    questionTopicText: {
      color: colors.darkBlue,
      fontSize: '35px',
      marginBottom: '40px',
      textAlign: 'center',
    },
    funcDescText: {
      fontWeight: 'bold',
      fontSize: '25px',
    },
    questionDescText: {
      color: 'gray',
      fontSize: '18px',
      paddingLeft: '20px',
      paddingRight: '20px',
    },
    questionDescExampleText: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '20px',
      padding: '20px',
    },
    questionDescCodeBlock: {
      padding: '20px',
      color: 'black',
      backgroundColor: colors.lighterGray,
      fontSize: '18px',
      fontFamily:
        'SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace',
      padding: '20px',
      width: '85%',
    },
    answerSolutionContainer: {
      marginTop: '30px',
    },
    questionAnswerButtonHighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.darkBlue,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
      fontWeight: 'bold',
    },
    questionAnswerButtonUnhighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.charcoalGray,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
    },
    questionAnswerButtonContainer: {
      display: 'flex',
      flexDirection: 'row',
      marginTop: '20px',
    },
    runCodeButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 4,
      padding: '2px 20px',
    },
    exitInterviewButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    consoleText: {
      color: 'white',
      marginLeft: '20px',
      fontSize: '25px',
    },
    outputText: {
      color: 'white',
      marginTop: '15px',
      paddingLeft: '20px',
      fontFamily: 'monospace',
      fontSize: '18px',
    },
    languageExitInterviewContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: '20px',
    },
    languageDropdownContainer: {
      marginRight: '25px',
      color: 'white',
    },
    languageDropDown: {
      color: 'white',
    },
    navbarDisplayFlex: {
      display: `flex`,
      justifyContent: `space-around`,
      marginRight: `45px`,
    },
    navBarContainer: {
      display: `flex`,
      justifyContent: `space-between`,
    },
    linkText: {
      textDecoration: `none`,
      color: `black`,
    },
    linkTextSelected: {
      textDecoration: `none`,
      color: `#516BF6`,
      fontWeight: `bold`,
    },
    nameAvatar: {
      display: `flex`,
      justifyContent: `space-around`,
    },
    userNameDiv: {
      fontSize: `16px`,
      color: `black`,
      marginLeft: `10px`,
    },
    createInterviewDialog: {
      display: `flex`,
      flexDirection: `column`,
      justifyContent: `space-around`,
      alignItems: `center`,
      padding: `80px`,
      height: `250px`,
      width: `400px`,
    },

    createInterviewTitle: {
      fontSize: `28px`,
      color: colors.darkBlue,
      fontWeight: 700,
      fontFamily: `Helvetica`,
      marginBottom: `30px`,
    },
    formControl: {
      margin: theme.spacing(1),
      minWidth: 250,
      minHeight: 100,
    },

    createWaitingRoomButton: {
      fontSize: `14px`,
      backgroundColor: colors.darkBlue,
      color: 'white',
      borderRadius: 25,
      height: `55px`,
      padding: `10px 50px`,
      fontWeight: 750,
    },
    waitingRoomDialogue: {
      display: `flex`,
      flexDirection: `column`,

      alignContent: `left`,
    },
    formControlWaitingRoom: {
      padding: `40px`,
      margin: theme.spacing(1),
      minWidth: 700,
      minHeight: 300,
    },
    selectEmpty: {
      marginTop: theme.spacing(2),
      textAlign: `center`,
      fontWeight: 650,
    },

    answerButton: {
      color: colors.darkBlue,
      borderColor: colors.lightGray,
      borderRadius: 5,
      marginTop: '10px',
      marginBottom: '20px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    answerButtonContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    continueButton: {
      background: colors.darkBlue,
      color: 'white',
      height: 48,
      padding: '0 30px',
      boxShadow: '0 3px 5px 2px rgba(125, 123, 135, .3)',
      marginLeft: '10px',
      borderRadius: 25,
      '&:hover': {
        backgroundColor: colors.darkBlue,
      },
    },
    redirectPageButton: {
      color: colors.darkGray,
      height: '5ch',
      padding: '0 30px',
      marginLeft: '10px',
      borderRadius: 25,
    },
    startDashboardButton: {
      borderRadius: 35,
      height: 40,
      width: 100,
      backgroundColor: colors.darkBlue,
      padding: '18px 36px',
      fontSize: '18px',
      color: 'white',
      marginTop: '30px',
      '&:hover': {
        backgroundColor: colors.darkBlue,
      },
    },
    feedbackDialog: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    feedbackDialogTitle: {
      color: colors.darkBlue,
      width: '450px',
      textAlign: 'center',
      fontWeight: '400',
      fontSize: '30px',
      marginBottom: '12px',
    },
    feedbackDialogSubheading: {
      marginTop: 0,
      color: colors.lightGray,
      fontWeight: '350',
      fontStyle: 'italic',
    },
    feedbackDialogQuestionNumber: {
      display: 'flex',
      marginBottom: '8px',
    },
    feedbackNumber: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
      marginRight: '2px',
    },
    feedbackRemainder: {
      color: colors.lightGray,
      fontSize: '16px',
    },
    feedbackQuestion: {
      color: colors.darkGraySolid,
      fontWeight: 'bold',
      fontSize: '16px',
      marginBottom: '30px',
    },
    feedbackFormContainer: {
      display: 'flex',
      marginTop: '20px',
      marginBottom: '20px',
    },
    feedbackFormLabel: {
      marginTop: 'auto',
      paddingBottom: '12px',
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
    },
    formRadioOne: {
      marginLeft: '20px',
      marginRight: '20px',
    },
    feedbackCategoryRatingsContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginBottom: '20px',
    },
    feedbackCategoryRatings: {
      textAlign: 'center',
      width: '82px',
      fontSize: '12px',
      marginLeft: '20px',
      marginTop: 'auto',
      color: colors.darkBlue,
      fontWeight: '600',
    },
    feedbackFormContainerRadio: {
      display: 'flex',
      width: '100%',
      justifyContent: 'space-between',
    },
    feedbackFormRadio: {
      alignSelf: 'flex-end',
    },
    feedbackFormContainerLabel: {
      marginLeft: '45px',
    },
    feedbackFormCategoryContainer: {
      display: 'flex',
      flexDirection: 'column',
      width: '100vh',
    },
    feedbackActions: {
      justifyContent: 'center',
      marginBottom: '25px',
      marginTop: '30px',
    },
    feedbackText: {
      width: '90vh',
    },
    feedbackError: {
      color: 'red',
      textAlign: 'center',
    },
    feedbackExperienceRating: {
      marginBottom: '50px',
    },
    feedbackExperienceRatingDesc: {
      marginTop: '20px',
      marginBottom: '20px',
      color: colors.darkBlue,
      borderRadius: '15px',
      boxShadow: '-4px -4px 4px #eae5e5',
      paddingLeft: '2px',
      paddingRight: '2px',
    },
    interviewActionButton: {
      borderRadius: 35,
      height: 20,
      width: 100,
      color: colors.darkGray,
      padding: '18px 36px',
      fontSize: '18px',
      fontWeight: 'bold',
      margin: '5px',
    },
    interviewQuestionTitle: {
      color: colors.darkBlue,
      fontSize: '16px',
      fontWeight: 'bold',
    },
    interviewNotStartedText: {
      color: 'black',
      fontSize: '16px',
      fontWeight: 'bold',
    },
    videoCallIcon: {
      height: '50px',
      width: '50px',
      color: 'white',
      marginRight: '20px',
    },
    videoChatBoxUser: {
      height: '100%',
      right: '0px',
      'z-index': 2,
      borderRadius: 15,
      bottom: '0px',
      position: 'absolute',
    },
    videoChatBoxPartner: {
      height: '100px',
      right: '0px',
      bottom: '0px',
      'z-index': 3,
      borderRadius: 15,
      position: 'absolute',
    },
    videoChatMainContainer: {
      right: '0px',
      'z-index': '1',
      position: 'absolute',
      width: '300px',
      height: '225px',
    },
    videoStreamContainer: {
      position: 'relative',
      width: '100%',
      height: '100%',
    },
    profileContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      height: '90vh',
    },
    profilePictureContainer: {
      display: 'flex',
      alignItems: 'center',
    },
    profileAvatar: {
      width: '60px',
      height: '60px',
      marginLeft: '15px',
    },
    changeAvatarButton: {
      marginLeft: 'auto',
    },
    profileHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: '40px',
      marginBottom: '40px',
      textAlign: 'center',
    },
    closeButton: {
      position: 'absolute',
      right: theme.spacing(1),
      top: theme.spacing(1),
      color: colors.darkGray,
    },
    waitingRoomUserName: {
      color: colors.charcoalGray,
      fontSize: `14px`,
      fontFamily: `Helvetica`,
    },
    waitingRoomAvatar: { marginRight: `10px` },
    linkAndCopy: { display: `flex` },
    waitingRoomDialogueTitle: {
      color: colors.darkBlue,
      fontSize: `25px`,
      marginBottom: `20px`,
      fontWeight: `bold`,
      fontFamily: `Helvetica`,
    },
    shareLink: {
      marginBottom: `5px`,
      fontWeight: `bold`,
    },
    urlLink: {
      fontFamily: `Helvetica`,
      fontSize: `14px`,
      padding: `25px`,

      // width: `50%`,
    },
    urlBox: {
      width: `60%`,
      // height: `100%`,
      marginBottom: `20px`,
    },
    participantsTitle: {
      color: colors.darkBlue,
      fontSize: `22px`,
      marginBottom: `20px`,
      fontWeight: `bold`,
      fontFamily: `Helvetica`,
    },
    participantsBox: {
      padding: `25px`,
      borderRadius: 4,
    },
    startInterviewButton: {
      marginTop: `25px`,
      backgroundColor: colors.darkBlue,
      height: `55px`,
      padding: `10px 50px`,
      color: `white`,
      borderRadius: 25,
      fontSize: `12px`,
      fontWeight: `bold`,
    },
    receivingCallText: {
      fontSize: '35px',
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      color: colors.darkBlue,
      marginBottom: '20px',
    },
    receivingCallNameAndAvatar: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoCallerName: {
      fontSize: '24px',
    },
    acceptCancelVideoButton: {
      borderRadius: 35,
      height: 40,
      width: 100,
      backgroundColor: colors.darkBlue,
      padding: '18px 50px',
      fontSize: '14px',
      color: 'white',
      marginTop: '5px',
      '&:hover': {
        backgroundColor: colors.darkBlue,
      },
    },
    receivingCallDialog: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-around',
      alignItems: 'center',
      padding: '30px',
      minHeight: 300,
      minWidth: 325,
    },
    formField: {
      display: 'flex',
      justifyContent: 'center',
      alignContent: 'center',
      flexDirection: 'column',
    },
    dashboardContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pastPracticesText: {
      fontSize: '40px',
      color: colors.darkBlue,
    },
    interviewTable: {
      width: 1000,
      margin: 'auto',
      borderWidth: 1,
      borderColor: 'black',
    },
    interviewTableHeader: {
      backgroundColor: colors.darkBlue,
    },
    headerFont: {
      color: 'white',
      fontSize: 15,
      fontWeight: 'bold',
    },
    infoFormDiv: {
      marginBottom: '2px',
      fontWeight: '600',
      //color: `${colors.darkGray}`,
      color: 'rgba(94, 94, 94)',
    },
    infoDropdown: {
      marginRight: '10px',
      marginBottom: '20px',
      paddingLeft: '16px',
      paddingBottom: '8px',
      paddingTop: '8px',
      borderRadius: '5px',
      border: `1px solid ${colors.lightGray}`,
      width: '100%',
      height: '40px',
    },
    starRating: {
      marginTop: '5px',
      marginBottom: '7px',
    },
    interviewLevelDiv: {
      color: `${colors.darkBlue}`,
      fontWeight: 'Bold',
    },
    interviewLevelDesc: {
      color: `${colors.darkGray}`,
      marginBottom: '30px',
    },
    interviewContainer: {
      overflow: 'hidden',
      height: '100%',
      width: '100vw',
      position: 'relative',
    },
    interviewHeader: {
      backgroundColor: colors.darkBlue,
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      height: '10vh',
      alignItems: 'center',
    },
    interviewDetailsContainer: {
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    interviewTextEditor: {
      backgroundColor: 'rgba(30,30,30, 1)',
      height: '100vh',
    },
    interviewOutput: {
      backgroundColor: colors.darkGraySolid,
      bottom: '0',
      position: 'absolute',
      height: '20vh',
      width: '66%',
      marginBottom: '25px',
      borderRadius: '10px',
    },
    interviewOutputHeader: {
      backgroundColor: colors.lightGraySolid,
      width: '100%',
      borderTopLeftRadius: '10px',
      borderTopRightRadius: '10px',
      height: '30%',
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
    },
    textMarginRight: {
      marginRight: '10px',
    },
    interviewWithText: {
      marginLeft: '40px',
      color: 'white',
      fontSize: '30px',
    },
    backgroundContainer: {
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `rgba(67, 67, 125)`,
    },
    background: {
      width: '50%',
      height: '80%',
      backgroundColor: `white`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      //justifyContent: "center",
    },
    backgroundHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: 'auto',
      marginBottom: 'auto',
    },
    backgroundForm: {
      width: '50%',
      //height: "30%",
      display: 'flex',
      flexDirection: 'column',
    },
    questionDetailsContainer: {
      marginTop: '30px',
      textAlign: 'left',
      width: '100%',
      height: '72vh',
      overflow: 'scroll',
    },
    questionTopicText: {
      color: colors.darkBlue,
      fontSize: '35px',
      marginBottom: '40px',
      textAlign: 'center',
    },
    funcDescText: {
      fontWeight: 'bold',
      fontSize: '25px',
    },
    questionDescText: {
      color: 'gray',
      fontSize: '18px',
      paddingLeft: '20px',
      paddingRight: '20px',
    },
    questionDescExampleText: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '20px',
      padding: '20px',
    },
    questionDescCodeBlock: {
      padding: '20px',
      color: 'black',
      backgroundColor: colors.lighterGray,
      fontSize: '18px',
      fontFamily:
        'SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace',
      padding: '20px',
      width: '85%',
    },
    answerSolutionContainer: {
      marginTop: '30px',
    },
    questionAnswerButtonHighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.darkBlue,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
      fontWeight: 'bold',
    },
    questionAnswerButtonUnhighlighted: {
      borderRadius: 35,
      height: 50,
      width: 180,
      padding: '18px 36px',
      fontSize: '15px',
      color: colors.charcoalGray,
      marginRight: '15px',
      boxShadow: `0 1px 5px 2px ${colors.shadow}`,
    },
    questionAnswerButtonContainer: {
      display: 'flex',
      flexDirection: 'row',
      marginTop: '20px',
    },
    runCodeButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 4,
      padding: '2px 20px',
    },
    exitInterviewButton: {
      color: 'white',
      borderColor: colors.lightGray,
      borderRadius: 25,
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    consoleText: {
      color: 'white',
      marginLeft: '20px',
      fontSize: '25px',
    },
    outputText: {
      color: 'white',
      marginTop: '15px',
      paddingLeft: '20px',
      fontFamily: 'monospace',
      fontSize: '18px',
    },
    languageExitInterviewContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: '20px',
    },
    languageDropdownContainer: {
      marginRight: '25px',
      color: 'white',
    },
    languageDropDown: {
      color: 'white',
    },
    navbarDisplayFlex: {
      display: `flex`,
      justifyContent: `space-around`,
      marginRight: `45px`,
    },
    navBarContainer: {
      display: `flex`,
      justifyContent: `space-between`,
    },
    linkText: {
      textDecoration: `none`,
      color: `black`,
    },
    linkTextSelected: {
      textDecoration: `none`,
      color: `#516BF6`,
      fontWeight: `bold`,
    },
    nameAvatar: {
      display: `flex`,
      justifyContent: `space-around`,
    },
    userNameDiv: {
      fontSize: `16px`,
      color: `black`,
      marginLeft: `10px`,
    },
    createInterviewDialog: {
      display: `flex`,
      flexDirection: `column`,
      justifyContent: `space-around`,
      alignItems: `center`,
      padding: `45px`,
    },
    waitingRoomDialogue: {
      display: `flex`,
      flexDirection: `column`,
      justifyContent: `space-between`,
      alignContent: `left`,
    },
    formControl: {
      margin: theme.spacing(1),
      minWidth: 450,
      minHeight: 100,
    },
    formControlWaitingRoom: {
      margin: theme.spacing(1),
      minWidth: 500,
      minHeight: 100,
    },
    selectEmpty: {
      marginTop: theme.spacing(2),
    },
    answerButton: {
      color: colors.darkBlue,
      borderColor: colors.lightGray,
      borderRadius: 5,
      marginTop: '10px',
      marginBottom: '20px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    answerButtonContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    continueButton: {
      background: colors.darkBlue,
      color: 'white',
      height: 48,
      padding: '0 30px',
      boxShadow: '0 3px 5px 2px rgba(125, 123, 135, .3)',
      marginLeft: '10px',
      borderRadius: 25,
    },
    redirectPageButton: {
      color: colors.darkGray,
      height: '5ch',
      padding: '0 30px',
      marginLeft: '10px',
      borderRadius: 25,
    },
    startDashboardButton: {
      borderRadius: 35,
      height: 40,
      width: 100,
      backgroundColor: colors.darkBlue,
      padding: '18px 36px',
      fontSize: '18px',
      color: 'white',
      marginTop: '30px',
    },
    feedbackDialog: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    feedbackDialogTitle: {
      color: colors.darkBlue,
      width: '450px',
      textAlign: 'center',
      fontWeight: '400',
      fontSize: '30px',
      marginBottom: '12px',
    },
    feedbackDialogSubheading: {
      marginTop: 0,
      color: colors.lightGray,
      fontWeight: '350',
      fontStyle: 'italic',
    },
    feedbackDialogQuestionNumber: {
      display: 'flex',
      marginBottom: '8px',
    },
    feedbackNumber: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
      marginRight: '2px',
    },
    feedbackRemainder: {
      color: colors.lightGray,
      fontSize: '16px',
    },
    feedbackQuestion: {
      color: colors.darkGraySolid,
      fontWeight: 'bold',
      fontSize: '16px',
      marginBottom: '30px',
    },
    feedbackFormContainer: {
      display: 'flex',
      marginTop: '20px',
      marginBottom: '20px',
    },
    feedbackFormLabel: {
      marginTop: 'auto',
      paddingBottom: '12px',
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
    },
    formRadioOne: {
      marginLeft: '20px',
      marginRight: '20px',
    },
    feedbackCategoryRatingsContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginBottom: '20px',
    },
    feedbackCategoryRatings: {
      textAlign: 'center',
      width: '82px',
      fontSize: '12px',
      marginLeft: '20px',
      marginTop: 'auto',
      color: colors.darkBlue,
      fontWeight: '600',
    },
    feedbackFormContainerRadio: {
      display: 'flex',
      width: '100%',
      justifyContent: 'space-between',
    },
    feedbackFormRadio: {
      alignSelf: 'flex-end',
    },
    feedbackFormContainerLabel: {
      marginLeft: '45px',
    },
    feedbackFormCategoryContainer: {
      display: 'flex',
      flexDirection: 'column',
      width: '100vh',
    },
    feedbackActions: {
      justifyContent: 'center',
      marginBottom: '25px',
      marginTop: '30px',
    },
    feedbackText: {
      width: '90vh',
    },
    feedbackError: {
      color: 'red',
      textAlign: 'center',
    },
    feedbackExperienceRating: {
      marginBottom: '50px',
    },
    feedbackExperienceRatingDesc: {
      marginTop: '20px',
      marginBottom: '20px',
      color: colors.darkBlue,
      borderRadius: '15px',
      boxShadow: '-4px -4px 4px #eae5e5',
      paddingLeft: '2px',
      paddingRight: '2px',
    },
    interviewActionButton: {
      borderRadius: 35,
      height: 20,
      width: 100,
      color: colors.darkGray,
      padding: '18px 36px',
      fontSize: '18px',
      fontWeight: 'bold',
      margin: '5px',
    },
    interviewQuestionTitle: {
      color: colors.darkBlue,
      fontSize: '16px',
      fontWeight: 'bold',
    },
    interviewNotStartedText: {
      color: 'black',
      fontSize: '16px',
      fontWeight: 'bold',
    },
    videoCallIcon: {
      height: '50px',
      width: '50px',
      color: 'white',
      marginRight: '20px',
    },
    videoChatBoxUser: {
      height: '100%',
      right: '0px',
      'z-index': 2,
      borderRadius: 15,
      bottom: '0px',
      position: 'absolute',
    },
    videoChatBoxPartner: {
      height: '100px',
      right: '0px',
      bottom: '0px',
      'z-index': 3,
      borderRadius: 15,
      position: 'absolute',
    },
    videoChatMainContainer: {
      right: '0px',
      'z-index': '1',
      position: 'absolute',
      width: '300px',
      height: '225px',
    },
    videoStreamContainer: {
      position: 'relative',
      width: '100%',
      height: '100%',
    },
    profileContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      height: '90vh',
    },
    profilePictureContainer: {
      display: 'flex',
      alignItems: 'center',
    },
    profileAvatar: {
      width: '60px',
      height: '60px',
      marginLeft: '15px',
    },
    changeAvatarButton: {
      marginLeft: 'auto',
    },
    profileHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: '40px',
      marginBottom: '40px',
      textAlign: 'center',
    },
    navBarContainer: {
      display: `flex`,
      justifyContent: `space-between`,
    },
    linkText: {
      textDecoration: `none`,
      color: `black`,
    },
    linkTextSelected: {
      textDecoration: `none`,
      color: `#516BF6`,
      fontWeight: `bold`,
    },
    nameAvatar: {
      display: `flex`,
      justifyContent: `space-around`,
    },
    userNameDiv: {
      fontSize: `16px`,
      color: `black`,
      marginLeft: `10px`,
    },
    createInterviewDialog: {
      display: `flex`,
      flexDirection: `column`,
      justifyContent: `space-around`,
      alignItems: `center`,
      padding: `45px`,
    },
    waitingRoomDialogue: {
      display: `flex`,
      flexDirection: `column`,
      justifyContent: `space-between`,
      alignContent: `left`,
    },
    formControl: {
      margin: theme.spacing(1),
      minWidth: 450,
      minHeight: 100,
    },
    formControlWaitingRoom: {
      margin: theme.spacing(1),
      minWidth: 500,
      minHeight: 100,
    },
    selectEmpty: {
      marginTop: theme.spacing(2),
    },
    answerButton: {
      color: colors.darkBlue,
      borderColor: colors.lightGray,
      borderRadius: 5,
      marginTop: '10px',
      marginBottom: '20px',
      fontWeight: 'bold',
      fontSize: '18px',
      borderWidth: 2,
      padding: '2px 20px',
    },
    answerButtonContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    continueButton: {
      background: colors.darkBlue,
      color: 'white',
      height: 48,
      padding: '0 30px',
      boxShadow: '0 3px 5px 2px rgba(125, 123, 135, .3)',
      marginLeft: '10px',
      borderRadius: 25,
    },
    redirectPageButton: {
      color: colors.darkGray,
      height: '5ch',
      padding: '0 30px',
      marginLeft: '10px',
      borderRadius: 25,
    },
    startDashboardButton: {
      borderRadius: 35,
      height: 40,
      width: 100,
      backgroundColor: colors.darkBlue,
      padding: '18px 36px',
      fontSize: '18px',
      color: 'white',
      marginTop: '30px',
    },
    feedbackDialog: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    feedbackDialogTitle: {
      color: colors.darkBlue,
      width: '450px',
      textAlign: 'center',
      fontWeight: '400',
      fontSize: '30px',
      marginBottom: '12px',
    },
    feedbackDialogSubheading: {
      marginTop: 0,
      color: colors.lightGray,
      fontWeight: '350',
      fontStyle: 'italic',
    },
    feedbackDialogQuestionNumber: {
      display: 'flex',
      marginBottom: '8px',
    },
    feedbackNumber: {
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
      marginRight: '2px',
    },
    feedbackRemainder: {
      color: colors.lightGray,
      fontSize: '16px',
    },
    feedbackQuestion: {
      color: colors.darkGraySolid,
      fontWeight: 'bold',
      fontSize: '16px',
      marginBottom: '30px',
    },
    feedbackFormContainer: {
      display: 'flex',
      marginTop: '20px',
      marginBottom: '20px',
    },
    feedbackFormLabel: {
      marginTop: 'auto',
      paddingBottom: '12px',
      color: colors.darkBlue,
      fontWeight: 'bold',
      fontSize: '16px',
    },
    formRadioOne: {
      marginLeft: '20px',
      marginRight: '20px',
    },
    feedbackCategoryRatingsContainer: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginBottom: '20px',
    },
    feedbackCategoryRatings: {
      textAlign: 'center',
      width: '82px',
      fontSize: '12px',
      marginLeft: '20px',
      marginTop: 'auto',
      color: colors.darkBlue,
      fontWeight: '600',
    },
    feedbackFormContainerRadio: {
      display: 'flex',
      width: '100%',
      justifyContent: 'space-between',
    },
    feedbackFormRadio: {
      alignSelf: 'flex-end',
    },
    feedbackFormContainerLabel: {
      marginLeft: '45px',
    },
    feedbackFormCategoryContainer: {
      display: 'flex',
      flexDirection: 'column',
      width: '100vh',
    },
    feedbackActions: {
      justifyContent: 'center',
      marginBottom: '25px',
      marginTop: '30px',
    },
    feedbackText: {
      width: '90vh',
    },
    feedbackError: {
      color: 'red',
      textAlign: 'center',
    },
    feedbackExperienceRating: {
      marginBottom: '50px',
    },
    feedbackExperienceRatingDesc: {
      marginTop: '20px',
      marginBottom: '20px',
      color: colors.darkBlue,
      borderRadius: '15px',
      boxShadow: '-4px -4px 4px #eae5e5',
      paddingLeft: '2px',
      paddingRight: '2px',
    },
    interviewActionButton: {
      borderRadius: 35,
      height: 20,
      width: 100,
      color: colors.darkGray,
      padding: '18px 36px',
      fontSize: '18px',
      fontWeight: 'bold',
      margin: '5px',
    },
    interviewQuestionTitle: {
      color: colors.darkBlue,
      fontSize: '16px',
      fontWeight: 'bold',
    },
    interviewNotStartedText: {
      color: 'black',
      fontSize: '16px',
      fontWeight: 'bold',
    },
    profileContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      height: '90vh',
    },
    profilePictureContainer: {
      display: 'flex',
      alignItems: 'center',
    },
    profileAvatar: {
      width: '60px',
      height: '60px',
      marginLeft: '15px',
    },
    changeAvatarButton: {
      marginLeft: 'auto',
    },
    profileHeader: {
      color: `${colors.darkBlue}`,
      fontSize: '25px',
      fontWeight: '600',
      width: '50%',
      marginTop: '40px',
      marginBottom: '40px',
      textAlign: 'center',
    },
  }),
  { index: 1 }
);

export const colors = {
  darkBlue: '#516BF6',
  lightBlue: 'rgba(73, 145, 203, .8)',
  darkGray: 'rgba(105, 105, 105, .8)',
  lightGray: 'rgba(169, 169, 169, .8)',
  shadow: 'rgba(125, 123, 135, .3)',
  charcoalGray: 'rgba(30,30,30, .8)',
  darkGraySolid: 'rgba(105, 105, 105, 1)',
  lightGraySolid: 'rgba(76, 76, 76, 1)',
  lighterGray: 'rgba(247, 249, 250, 1)',
};
